// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2R8CFkmrHgi80W5Sgi5yBGvJg4-BMlMs',
    appId: '1:131581578880:web:c79de7c8096910a2ace065',
    messagingSenderId: '131581578880',
    projectId: 'manize-app',
    authDomain: 'manize-app.firebaseapp.com',
    storageBucket: 'manize-app.appspot.com',
    measurementId: 'G-B35E68E4VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8c8fd8kf7ItBYEfqRJXTWoZoTkM3bSZE',
    appId: '1:131581578880:android:237f835a8792ab1cace065',
    messagingSenderId: '131581578880',
    projectId: 'manize-app',
    storageBucket: 'manize-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkUQPE9s7Yey6n7DEVYCzYBbBsP7_U01w',
    appId: '1:131581578880:ios:6419f2c10a73761bace065',
    messagingSenderId: '131581578880',
    projectId: 'manize-app',
    storageBucket: 'manize-app.appspot.com',
    iosClientId: '131581578880-pnc4d15je5uhdeth614l853nce3lg3s5.apps.googleusercontent.com',
    iosBundleId: 'ir.manize.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkUQPE9s7Yey6n7DEVYCzYBbBsP7_U01w',
    appId: '1:131581578880:ios:6419f2c10a73761bace065',
    messagingSenderId: '131581578880',
    projectId: 'manize-app',
    storageBucket: 'manize-app.appspot.com',
    iosClientId: '131581578880-pnc4d15je5uhdeth614l853nce3lg3s5.apps.googleusercontent.com',
    iosBundleId: 'ir.manize.app',
  );
}
